Feature/signup
shinonome-inc/backend-final-assignment-sugaya pull request #1
Opened 2023-08-16 17:10 UTC by coder-rarara

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-17 15:32 UTC, khimoo commented on accounts/models.py
>  # class FriendShip(models.Model):
使ってないコメントは消して大丈夫です！
model.py以外にもurls.pyやviews.pyのimport文のコメントアウトは消していいです。

2023-08-17 22:06 UTC, coder-rarara commented on accounts/models.py
>  # class FriendShip(models.Model):
import文のコメントアウトを消しました。ご確認よろしくお願いします！

2023-08-20 05:47 UTC, gaato requested changes

2023-08-20 05:47 UTC, gaato commented on .flake8
> +extend-exclude = .env/,env/,**/migrations/*,manage.py,asgi.py,wsgi.py
venv 環境を `.env` あるいは `env` という名前で作ったということで合っていますか？
それならそれで良いのですが今後レビュワーが気づかない可能性が高いので `.venv` や `venv` も書いて置いてください。

2023-08-20 05:47 UTC, gaato commented on accounts/tests.py
> +        self.assertIn("同じユーザー名が既に登録済みです。", form.errors["username"])
１回目の POST リクエストが成功することを検証してください。

2023-08-20 05:47 UTC, gaato commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(password=invalid_data["password2"]).exists())
平文のパスワードはデータベースに保存されていない（ハッシュ化して保存している）のでこれは成功していても常に False を返します。
よってこのアサーションは意味がないので消してください。パスワードのバリデーションエラーをテストするときはフォームのエラーメッセージを確認すれば OK です。
他のパスワードに関するテストでも同様です。

2023-08-20 06:46 UTC, coder-rarara commented on .flake8
> +extend-exclude = .env/,env/,**/migrations/*,manage.py,asgi.py,wsgi.py
了解です！次回からそのようにします！

2023-08-20 06:47 UTC, coder-rarara commented on accounts/tests.py
> +        self.assertIn("同じユーザー名が既に登録済みです。", form.errors["username"])
修正しました！

2023-08-20 06:47 UTC, coder-rarara commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(password=invalid_data["password2"]).exists())
勉強になります。修正しました！

2023-08-20 07:01 UTC, gaato approved these changes

2023-08-20 07:01 UTC, gaato commented
LGTM！

2023-08-20 07:02 UTC, merged