ツイート機能の実装
shinonome-inc/backend-final-assignment-sugaya pull request #3
Opened 2023-09-13 14:50 UTC by coder-rarara

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-19 12:48 UTC, kotasuzuki72 requested changes
現状の実装では、Djangoの管理画面(/admin/)においてモデルの作成や編集を行うことができません。
tweets/admin.pyにおいて、admin.site.registerにTweetのモデルを入れてください。

2023-09-19 12:48 UTC, kotasuzuki72 commented on templates/accounts/user_profile.html
> +
こちらのページは、urlに打ち込む以外に到達する方法はありますか？
もしなければ、Tweetのユーザー名をクリックすると飛んでこれるようにすると良いと思います。
変更は任意です。

2023-09-21 16:11 UTC, coder-rarara commented on templates/accounts/user_profile.html
> +
2つとも修正しました！

2023-09-22 09:10 UTC, kotasuzuki72 commented
LGTM

2023-09-25 02:53 UTC, Snak21-FPB requested changes
コード外で２件と、コード内で４件コメントしました。
```
レビューコメントの意味
[must] 修正必須。要件を満たしていなかったり、アプリとして使う上で重要なコメントを書いています。
[imo] 修正任意。レビュワーの意見を書いています。
[nits] 修正任意。imoより重要度が低い、細かい点のコメントを書いています。
[next] 修正不要。最終課題をクリアした後に見直してみてほしい発展的なコメントを書いています。
[good] 修正不要。良いと思ったところにコメントを書いています。
```
- [must] Userモデルが管理画面から見えないようなので、管理画面に登録してください。
- [must] Homeビューにアクセスできるリンクが見当たらないので、各画面に追加してください。

2023-09-25 02:53 UTC, Snak0201 commented on templates/tweets/create.html
> +  {{form.as_p}}
```suggestion
  {{ form.as_p }}
```
[nits] タグは1スペース空けたほうが見やすいです（ほかの部分と統一もされます）

2023-09-25 02:53 UTC, Snak21-FPB commented on templates/tweets/home.html
> +  <li><a href="{% url 'tweets:detail' tweet.pk %}">詳細</a></li>
```suggestion
  <li><a href="{% url 'tweets:detail' tweet.id %}">詳細</a></li>
```
[nits] こちらのほうが個人的には好みです。ツイートのIDを取得するということが明示できます。今回の場合、ほかが`pk`で統一されているのでここを直す必要はないかと思います。

2023-09-25 02:53 UTC, Snak21-FPB commented on tweets/tests.py
> +        self.assertFormError(response, "form", "content", "このフィールドは必須です。")
[must] [Djangoのドキュメント](https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase.assertFormError)によると、`assertFormError`はdeprecated（非推奨・将来削除予定）になっています。`assertIn`や`assertEqual`を使って書き換えてみてください（ほかの`assertFormError`を使っているところも同様です）。

2023-09-25 02:53 UTC, Snak21-FPB commented on mysite/settings.py
> +HOME_URL = "tweets:home"
[good] このようにsettingsで定数を定義してtestなどで読み込んで使うのはよい工夫だと思います。名前空間を変えたときにここだけを変えればよくなるためです（名前空間を変えることはしないほうが良いのですが）。

2023-09-25 21:40 UTC, coder-rarara commented on templates/tweets/create.html
> +  {{form.as_p}}
mustを3つと、上記nitsに付いて修正しました！

2023-09-26 00:56 UTC, Snak21-FPB approved these changes
Approved🔵

2023-09-26 01:00 UTC, merged