フォロー機能の実装
shinonome-inc/backend-final-assignment-sugaya pull request #4
Opened 2023-11-12 07:18 UTC by coder-rarara

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-11-12 08:12 UTC, kotasuzuki72 approved these changes

2023-11-12 08:12 UTC, kotasuzuki72 commented on accounts/models.py
> +            CheckConstraint(check=~Q(from_user=F("to_user")), name="not_follow_myself"),
CheckConstraint使っていて良いと思います。

2023-11-12 08:12 UTC, kotasuzuki72 commented on accounts/views.py
> +            return HttpResponseBadRequest("自分自身はフォローできません。")
エラーメッセージを表示できていて良いと思います。

2023-11-12 08:12 UTC, kotasuzuki72 commented on accounts/views.py
> +class FollowingListView(ListView):
ListView使えていて良いと思います。

2023-11-14 01:08 UTC, Snak-DLB requested changes
いくつかコメントをしたのでご確認ください。チェックボックスのついているものは修正必須、(任意)とあるものは修正するかどうかお任せします。

- [ ] `TestHomeView`の`setUp`メソッド内では、`Tweet.objects.create(...)`の形でツイートを作った方が良いと思います。また、`assertRedirects`は不要に見えます。
  - `setUp`はすべてのテストの前に1回ずつ実行され、そのたびにここが動作するためです。また、Tweetを作ることに関してのテストは他の部分で実装されており、重複するという点もあります。

2023-11-14 01:08 UTC, Snak0201 commented on accounts/views.py
> +        )
- [x] フォロー・被フォローの新しい順で並べることをコード上で明示した方が良いです

2023-11-14 01:08 UTC, Snak0201 commented on templates/accounts/user_profile.html
> +{% endif %}
- (任意) 自分自身はフォローできないので、ボタンも消しておく方が良いと思います

2023-11-14 01:08 UTC, Snak0201 commented on accounts/tests.py
> +        response = self.client.get(self.url)
- (任意) この`self.url`はここでしか使っていないので、下のように書いても良いかと思います（もっとも、コードが横に長くなるので好みの問題ではあります）
```suggestion
        response = self.client.get(reverse("accounts:user_profile", kwargs={"username": self.user2.username}))
```

2023-11-14 01:08 UTC, Snak0201 commented on accounts/tests.py
> +        )
- [x] 内容が同じテストが２つあるようなので、どちらかは取り除いてください
- [x] 自分へのフォロー解除についてのテストを追加してください

2023-11-17 01:56 UTC, Snak-DLB approved these changes

2023-11-17 01:57 UTC, merged